language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7

before_install:
 - if [[ ! -f "cmake-3.4.3-Linux-x86_64/bin/cmake" ]]; then wget --no-check-certificate http://cmake.org/files/v3.4/cmake-3.4.3-Linux-x86_64.tar.gz && tar -xvf cmake-3.4.3-Linux-x86_64.tar.gz; fi
# - mkdir build && cd build
# - ../cmake-3.4.3-Linux-x86_64/bin/cmake ..
# - ../cmake-3.4.3-Linux-x86_64/bin/cmake --build . --config Release
# - ../cmake-3.4.3-Linux-x86_64/bin/cmake --build . --config Debug

install:
 - alias gcc=$COMPILER
 - pwd
 - LLVM_DIR=`pwd`
 - cd ..
 - mkdir llvm-build && cd llvm-build
 - $LLVM_DIR/cmake-3.4.3-Linux-x86_64/bin/cmake -G "Unix Makefiles" $LLVM_DIR
 - make

