language: cpp

install:
 - pwd
 - LLVM_DIR=`pwd`
 - cd ..
 - mkdir llvm-build
 - cd llvm-build
 - cmake -G "Unix Makefiles" $LLVM_DIR
 - make

addons:
    apt:
      packages:
        - cmake
      sources:
        - kalakris-cmake
